### ISSUE TITLE
Fix step# 3 in "No Fail Quick Start" instructions

### ISSUE THREAD

**Issue by omveda** [securesign/sigstore-ocp#12]
In step# 3 of "No fail quick start in 5 steps", the instruction for substituting the base_domain should be reversed.
Correct substitution:
:%s/rosa.p9esn-qgkm3-wkk.o7au.p3.openshiftapps.com/rosa.*.com/g

**Comment by cooktheryan** [comment]
@sallyom ^^

**Comment by sallyom** [comment]
updated, made the instructions more generic for that step
